import re
from snakebids import bids
from os.path import join
import pandas as pd

from snakebids import set_bids_spec

set_bids_spec("v0_0_0")

configfile: "config/config.yml"

#import snakebatch workflow
module snakebatch:
    snakefile:
        github("akhanf/snakebatch", path="workflow/Snakefile", tag="4b0d1ac")
    config: config["snakebatch"]


use rule * from snakebatch as snakebatch_*

wildcard_constraints:
    subject='[0-9a-zA-Z]+'

#rest of the workflow
if config["use_test_subjects"]:
    subjects = config["test_subjects"]
else:
    subjects = {
        dataset: list(
            pd.read_csv(
                f"resources/dataset-{dataset}_subjects.tsv",
                sep="\t",
                dtype={"participant_label": str},
            ).participant_label
        )
        for dataset in config['datasets']
    }



root = os.path.join(os.path.expandvars(config["root"]), "{dataset}")
in_root = os.path.expandvars(config["in_root"])


include: "rules/common.smk"
include: "rules/atlas.smk"
include: "rules/dwi.smk"
include: "rules/func.smk"
include: "rules/hippunfold.smk"
include: "rules/tabular.smk"
include: "rules/plotting.smk"

rule all_dwi_conn:
    input:
        get_dwi_conn_csv_targets(),
#    default_target: True





rule all_dwi:
    input:
        get_dwi_targets(),



rule all_lists:
    input:
        expand("resources/dataset-{dataset}_subjects.tsv", dataset=config["datasets"]),



