
in_root: '$HOME/graham' #for cbs server
#in_root: '/home/akhanf' #for graham

subsampling:
  epi:
    - shell0subsampled6
    - shell1000subsampled26
    - shell2000subsampled26
  mediumcs:
    - shell0
    - shell1000
    - shell2000
  strongcs:
    - shell0
    - shell1000
    - shell2000
  lightcs:
    - shell0
    - shell1000
    - shell2000
  lightcsnomoco:
    - shell0
    - shell1000
    - shell2000

#files in one big zip file - these paths are relative to in_root defined above
in_agg_zip: 
  snakebatch_dwi:
    HCP: 'projects/ctb-akhanf/cfmm-bids/Khan/LOBE/derivatives/snakebatch_LOBE_HCP_2023_09_23.zip'
    LOBE: 'projects/ctb-akhanf-ab/cfmm-bids/Khan/LOBE/derivatives/snakebatch_LOBE_2024_03_19.zip'
  snakebatch:
    HCP: 'projects/ctb-akhanf-ab/cfmm-bids/Khan/LOBE/derivatives/snakebatch_HCP_snakeanat_fmriprep_2024_03_21.zip'
    LOBE: 'projects/ctb-akhanf-ab/cfmm-bids/Khan/LOBE/derivatives/snakebatch_LOBE_2024_03_19.zip'

in_demog_tabular:
  HCP: 'projects/ctb-akhanf/ext-data/hcp_development/HCPDevImagingManifestBeh/ndar_subject01.txt'


  

#to find paths below, use: unzip -l cfmm-bids/Khan/LOBE/derivatives/snakebatch_LOBE_HCP_2023_09_23.zip | less
input_path: 
  dwi_nii: 
    strongcs: /local/scratch/compare_dwi/P156_test_corey_diffusion/cs_strong/cb_sp2d_diff_preproc_LTE.nii.gz
    mediumcs: '/local/scratch/compare_dwi/P156_test_corey_diffusion/cs_medium/cb_sp2d_diff_preproc_LTE.nii.gz'
    lightcs: /local/scratch/compare_dwi/P156_test_corey_diffusion/orig_withEddyMoco/cb_sp2d_diff_preproc_LTE.nii.gz
    lightcsnomoco: '/local/scratch/compare_dwi/P156_test_corey_diffusion/cb_sp2d_diff_cx_dndgabs_LTE.nii.gz'
    epi: '/local/scratch/compare_dwi/out_snakedwi/snakedwi/sub-P156/dwi/sub-P156_desc-eddy_dwi.nii.gz'
    
  dwi_mask: 
    strongcs: /local/scratch/compare_dwi/P156_test_corey_diffusion/cs_strong/brain_mask.nii.gz
    mediumcs: /local/scratch/compare_dwi/P156_test_corey_diffusion/cs_medium/brain_mask.nii.gz
    lightcs: /local/scratch/compare_dwi/P156_test_corey_diffusion/orig_withEddyMoco/brain_mask.nii.gz
    lightcsnomoco: '/local/scratch/compare_dwi/P156_test_corey_diffusion/mask_epi_resampled.nii.gz'
    epi: '/local/scratch/compare_dwi/out_snakedwi/snakedwi/sub-P156/dwi/sub-P156_desc-brain_mask.nii.gz'

  t1_nii: '/local/scratch/compare_dwi/out_snakedwi/snakedwi/sub-P156/anat/sub-P156_desc-preproc_T1w.nii.gz'
  surf_gii_t1: '/home/ROBARTS/alik/graham/scratch/3_processing/snakebatch_dwi_compare_snsx/SNSX/derivatives/snakeanat/sourcedata/ciftify/sub-{subject}/T1w/fsaverage_LR32k/sub-{subject}.{hemi}.{surf}.32k_fs_LR.surf.gii'
  surf_gii_mni: '/home/ROBARTS/alik/graham/scratch/3_processing/snakebatch_dwi_compare_snsx/SNSX/derivatives/snakeanat/sourcedata/ciftify/sub-{subject}/MNINonLinear/fsaverage_LR32k/sub-{subject}.{hemi}.{surf}.32k_fs_LR.surf.gii'
  hippunfold_vol_tsv: 'snakebatch/{dataset}/derivatives/hippunfold/hippunfold/sub-{subject}/anat/sub-{subject}_space-cropT1w_desc-subfields_atlas-bigbrain_volumes.tsv'



#this is the output folder
root: results

subj_wildcards:
  subject: '{subject}'


datasets:
  - lightcsnomoco
  - lightcs
  - mediumcs
  - strongcs
  - epi

use_test_subjects: True

test_subjects: 
 - P156

template_surf: 'resources/tpl-fsLR/tpl-fsLR_den-32k_hemi-{hemi}_{surf}.surf.gii'

#atlases to actually use:
atlases:
  - schaefer


atlas:
  schaefer: 
    dlabel: resources/schaefer_2018/Schaefer2018_300Parcels_7Networks_order.dlabel.nii
    network_pattern: '[^_]+_[^_]+_([^_]+)' #regex to find network name within label
  mmp: 
    dlabel: resources/mmp/Q1-Q6_RelatedParcellation210.CorticalAreas_dil_Final_Final_Areas_Group_Colors.32k_fs_LR.dlabel.nii
  brainnetome: 
    dlabel: resources/brainnetome/fsaverage.BN_Atlas.32k_fs_LR_updated.dlabel.nii
dwi:

  shells: 
    - '0'
    - '1000'
    - '2000'

  lmax: 
    - '0'
    - '4'
    - '4'

  sl_count: 1000000

 
func:

  fwhm:
    - 5
  

  task:
    - rest

  parcellation:    
    do_exclude_outliers: False
    n_stdevs_exclude: 2

  correlation:
    do_fisher_z: False
  denoise:
    24HMP8PhysSpikeReg:
      clean_img_opts:
        standardize: True
        detrend: False
        low_pass: 0.08
        high_pass: 0.01
      confounds_name:
        - csf 
        - csf_derivative1 
        - csf_derivative1_power2
        - csf_power2 
      confounds_like:
        - white_matter
        - trans
        - rot
        - motion_outlier
        - steady_state_outlier


nichord:
  struc:
    edge_widthscale: 0.001
  func:
    edge_widthscale: 0.001

netplotbrain:
  struc:
    view: 'LSc'
    edge_thresholddirection: above
    edge_threshold: 100
    edge_widthscale: 0.001


  func:
    view: 'LSc'
    edge_thresholddirection: above
    edge_threshold: 0.9
    edge_widthscale: 0.3


singularity:
  mrtrix: 'docker://mrtrix3/mrtrix3:3.0.4'
  diffparc: 'docker://khanlab/diffparc-deps:v0.1.0-fix'  

